import datetime
import hashlib
from sqlalchemy import Column, Integer, String, Float, Boolean, DateTime, Text, ForeignKey, JSON
from sqlalchemy.orm import relationship
from app.database import Base

class MippUser(Base):
    __tablename__ = "mipp_users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True)
    name = Column(String)
    role = Column(String, default="STARTUP") # GOVERNMENT, STARTUP, EVALUATOR, VALIDATOR, ADMIN
    department_name = Column(String, nullable=True)
    dpiit_number = Column(String, nullable=True)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

class MippChallenge(Base):
    __tablename__ = "mipp_challenges"

    id = Column(String, primary_key=True, index=True) # e.g. CH-2026-PUNE-01
    title = Column(String, index=True)
    department = Column(String)
    domain = Column(String)
    domain_label = Column(String)
    budget = Column(String)
    budget_num = Column(Float, default=12000000.0)
    pilot_timeline = Column(String)
    deadline = Column(String)
    status = Column(String, default="PUBLISHED") # DRAFT, UNDER_REVIEW, PUBLISHED, ARCHIVED
    applicant_count = Column(Integer, default=0)

    # 23 Outcome-Based Fields generated by AI Copilot
    problem_statement = Column(Text)
    current_situation = Column(Text)
    desired_outcome = Column(Text)
    target_beneficiaries = Column(Text)
    scope = Column(Text)
    out_of_scope = Column(Text)
    expected_solution_type = Column(Text)
    primary_kpi = Column(String)
    baseline_value = Column(String)
    target_value = Column(String)
    kpi_explanation = Column(Text)
    pilot_duration_months = Column(Integer, default=6)
    eligibility_criteria = Column(Text)
    evaluation_criteria = Column(Text)
    data_requirements = Column(Text)
    cybersecurity_requirements = Column(Text)
    ip_requirements = Column(Text)
    risk_classification = Column(String, default="MEDIUM")
    risk_mitigation = Column(Text)
    evidence_requirements = Column(Text)
    pilot_milestones = Column(Text)
    success_criteria = Column(Text)
    scale_criteria = Column(Text)

    # Quality Score (0-100)
    quality_score = Column(Integer, default=91)
    quality_breakdown = Column(JSON, nullable=True)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

class MippStartup(Base):
    __tablename__ = "mipp_startups"

    id = Column(String, primary_key=True, index=True) # ST-001
    name = Column(String, index=True)
    dpiit_number = Column(String)
    founded_year = Column(Integer)
    location = Column(String)
    founder = Column(String)
    sector = Column(String)
    stage = Column(String)
    team_size = Column(Integer)
    website = Column(String)
    summary = Column(Text)
    past_work = Column(Text)
    certifications = Column(JSON)
    past_pilots_count = Column(Integer, default=3)
    maharashtra_presence = Column(Boolean, default=True)

    # Capability Ratings (0-100)
    technical_readiness = Column(Integer, default=92)
    government_readiness = Column(Integer, default=90)
    pilot_readiness = Column(Integer, default=94)
    security_readiness = Column(Integer, default=95)
    deployment_readiness = Column(Integer, default=88)
    operational_readiness = Column(Integer, default=89)

class MippPilot(Base):
    __tablename__ = "mipp_pilots"

    id = Column(String, primary_key=True, index=True) # PL-2026-PUNE-01
    challenge_id = Column(String, ForeignKey("mipp_challenges.id"))
    startup_id = Column(String, ForeignKey("mipp_startups.id"))
    department = Column(String)
    district = Column(String, default="Pune")
    status = Column(String, default="DEPLOYMENT") # DRAFT, APPROVED, DEPLOYMENT, VALIDATION, COMPLETED, SCALED
    rag_status = Column(String, default="GREEN") # RED, AMBER, GREEN
    total_budget = Column(Float, default=12000000.0)
    released_budget = Column(Float, default=4800000.0)
    progress_pct = Column(Integer, default=65)

    # Post-Pilot Verified Metrics
    kpi_achievement_pct = Column(Float, default=113.0)
    timeline_status = Column(String, default="ON_TIME")
    budget_variance_pct = Column(Float, default=2.0)
    security_pass = Column(Boolean, default=True)
    independent_validation_pass = Column(Boolean, default=True)
    scale_readiness_score = Column(Integer, default=92)
    scale_decision = Column(String, default="READY_FOR_SCALE")

class MippMilestone(Base):
    __tablename__ = "mipp_milestones"

    id = Column(String, primary_key=True, index=True) # M1..M5
    pilot_id = Column(String, ForeignKey("mipp_pilots.id"))
    title = Column(String)
    percentage = Column(Float)
    amount = Column(Float)
    due_date = Column(String)
    status = Column(String, default="APPROVED") # NOT_DUE, PENDING_EVIDENCE, UNDER_REVIEW, APPROVED, RELEASED
    payment_status = Column(String, default="RELEASED")
    evidence_required = Column(String)

class MippEvidence(Base):
    __tablename__ = "mipp_evidence"

    id = Column(String, primary_key=True, index=True)
    pilot_id = Column(String, ForeignKey("mipp_pilots.id"))
    title = Column(String)
    evidence_type = Column(String) # CSV, PDF, Image, Sensor Data, System Logs
    uploader_role = Column(String)
    uploaded_at = Column(String)
    sha256_checksum = Column(String)

    # 4-Way Verification Values
    startup_claimed_val = Column(Float, default=35.0)
    govt_observed_val = Column(Float, default=29.0)
    evaluator_assessed_val = Column(Float, default=31.0)
    independent_validator_val = Column(Float, default=28.0)
    verified_result = Column(String, default="29% Average Congestion Delay Reduction")

    confidence = Column(String, default="HIGH") # LOW, MEDIUM, HIGH
    verification_status = Column(String, default="VERIFIED") # SUBMITTED, VERIFIED, PARTIALLY_VERIFIED

class MippAuditLog(Base):
    __tablename__ = "mipp_audit_logs"

    id = Column(Integer, primary_key=True, autoincrement=True)
    actor = Column(String)
    role = Column(String)
    action = Column(String)
    entity = Column(String)
    entity_id = Column(String)
    timestamp = Column(DateTime, default=datetime.datetime.utcnow)
    sha256_hash = Column(String)

    def generate_hash(self):
        raw = f"{self.actor}:{self.action}:{self.entity}:{self.entity_id}:{self.timestamp}"
        return hashlib.sha256(raw.encode("utf-8")).hexdigest()
